### ISSUE TITLE
list of issues

### ISSUE THREAD

**Issue by ZoltanOnody** [TIS2017/Nobelisti#17]
ostatne:
- [ ] mat 1 delete modal na kazdom webe a posielat tam udaje cez JS (zatial vygenerujeme pre kazdy riadok tabulky samostatny modal) (to iste s unassign)
- [x] customize forms design
- [x] prerobit formulare
- [x] doplnit cudzie kluce do databazy
- [ ] posielanie textu do modal buttonu (Assign/Delete)
- [x] preco sa to vola `setOrganizerId` ket sa tam posiela cela entita a nie len id -> prepisat nazvy vsade
- [x] event_type slug musi mat validator pre slug.
- [x] slug v event_type nema byt menitelny!!! #102 
- [x] skontrolovat vikine innerjoiny, a skontrolovat nazvy premennych v navrhu a v databaze, nesedia.

# Auth #19 
- [x] vytvorit tabulku Admin (doctrin entita)
- [x] login controller (aj s logout)

# Admin 
- [x] vsetky stranky musia vyzadovat login
- [x] vytvorit zakladnu kostru s dizajnom #18

## Admins
- [x] entita admin #24 
- [x] add #31 #33 
- [x] edit fieldov #36 
- [x] edit hesla #75 
- [x] list all #31 
- [x] delete (with modal) #36 

## Language #45 #54 
- [x] entita language
- [x] list all
- [x] add new/edit
- [x] delete (with modal)

## Organizer #25 
- [x] entita organizer
- [x] add/edit
- [x] list all
- [x] filter
- [x] delete (with modal)

## Event type #42 
- [x] entita event_type
- [x] list
- [x] add
- [x] edit
- [x] delete (with modal)

## Mailing list #46 
- [x] entita registration
- [x] entita attendee
- [x] filter
- [x] show all
- [x] pagination

## Event #43 
- [x] entita event
- [x] entita eventOrganizers
- [x] entita eventLanguages
- [x] prepojenie entit navzajom vztahmi many-to-one a one-to-many
- [x] list events in table
- [x] vytvorit event_type_languages tabulku
- [x] list event_type_languages in table 
- [x] assign/unassign event_type language
- [x] add event
- [x] edit event (iba update dat) 
- [x] edit event -assign/unassign organizer k eventu (+ autocomplete)
- [x] edit event -assign/unassign language k eventu
- [x] delete event

# Template testing

## Email testing #86
- [x] steps:
   1. [x] vyvorit testovacieho ucastnik
   2. [x] kazdy jeden typ emailu, vyrenderuje a prida do message queue (prijmatel: email z formulara)
        - [x] registracny
        - [x] info o novej prednaske
        - [x] info pred prednaskou

## Web testing #84
- [x] zisti ci kazdy jazyk z events sa nachadza v subore templates

- [x] vacsi test (vyrenderuje linky):
    - [x] /test/event_slug?state=registration_not_started&lang=sk_SK
    - [x] /test/event_slug?state=registration_open&lang=sk_SK
    - [x] /test/event_slug?state=registration_finished&lang=sk_SK
    - [x] /test/event_slug?state=registration_no_capacity&lang=sk_SK

# Emaily
- [x] vytvorit entitu email_content, email_status
- [x] format messageov (s ktorymi sa bude pracovat)
- [x] vytvorit interface na odosielanie emailov (pridavanie do queue)
- [x] vytvorit message queue workera

## emaily pre organizatorov
- [x] vytvorit informacny email o ludoch prihlasenych na konkretnu udalost (raz denne ho posielat) #99 

# CRON #99
- [x] raz za hodinu pozriet ci este nema odoslat notifikacne emaily o tom, ze o 24h sa kona udalost
- [x] raz za den ma poslat emaily organizatorom
- [x] raz za cas zmazat rezervovane (no nepotvrdene) listky
- [x] schedule commands with cron #118 

# Vseobecne weby (nezalezi od templatu)
- [x] uvodna stranka na `/` #102 
- [x] stranka kde sa da zobrazi info o odhlaseni z mailing listu #81 #97 
- [x] stranka kde sa da zobrazi info o potvrdeni listka (uspesnom/neuspesnom) #82
- [x] registracia (ukladanie do db, vytvaranie attendee, kontrola existujucich attendee, kontrola kapacity, kontrola konca registracie) #82 #93

# Templates
- [x] vyrenderovat template s registraciou & todos from #78 
- [x] vytvorit ukazkovy template
- [x] vyhodit chybu pri missing jazykoch
