### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by viktorria** [TIS2017/Nobelisti#47]
- [x] zjednotit url, mena path
- [x] zjednotit nazvy CRUD metod v controlleroch
- [x] zmazat nepotrebne branche
- [x] dohodnut sa na zatvorkach, ci budu na riadku s definiciou. co uz s vygenerovanymi?

**Comment by ZoltanOnody** [comment]
navrhujem: 

| URL                       | path name         | metoda     | funkcia        | vysvetlenie                  |
|---------------------------|-------------------|------------|----------------|------------------------------|
| `/organizers`               | organizers  | GET        | `indexAction`  | zoznam organizatorov         |
| `/organizers/add`           | organizers_add    | GET + POST | `createAction` | pridanie noveho organizatora |
| `/organizers/edit/<id>`     | organizers_edit   | GET + POST | `editAction`   | upravovanie organizatora     |
| `/organizers/delete/<id>`   | organizers_delete | POST       | `deleteAction` | zmazanie organizatora        |

**Comment by viktorria** [comment]
Ok super, poprosim este nazvy pathov, aby to uz bolo dokonale :)

**Comment by ZoltanOnody** [comment]
HTML konzistencia, prosim dodrzme nasledovne pravidla:

- riadok nepresiahne 120 znakov 
- odsadzujeme 4 medzerami
- pouzivajme medzeri v `{{ premenna }}` nemiesto `{{premenna}}`
- v kazdom vnorenom bloku treba odsadzovat
- mena templatov, template nech sa vola podla funkcie ktora ju renderuje (bez sufixu Action). priklad: `/organizers` renderuje `indexAction`, template sa teda bude nachadzat vo `views/Organizers/index.html.twig` (edit: doplnene s - Andrej)

**Comment by ZoltanOnody** [comment]
> dohodnut sa na zatvorkach, ci budu na riadku s definiciou. co uz s vygenerovanymi?

toto za nas dohodol PHPCSFixer, zatvorky sa davaju na novy riadok.
