### ISSUE TITLE
dalsi todo list

### ISSUE THREAD

**Issue by ZoltanOnody** [TIS2017/Nobelisti#95]
Presiel som si poziadavky a nesplname este tieto veci, prosim assignme si ich a dokoncime ich!

Zo suboru https://github.com/TIS2017/Nobelisti/blob/master/docs/katalog/prvotne-zadanie.pdf
- [x] pridat `date_registration_opened` #98
- [x] template for registration open 'registration_open.{txt|yaml.html}.twig'
- [x] v den v `date_registration_opened` den rozoslat iba subscribnutym ludom registracne emaily! (R-1-1) #99 
- [x] pridat do kazdeho emailu link na odhlasenie z mailing listu + spojazdnit to (R-1-1-1) #97 
- [x] `date_registration_closes` pridat do DB a nakodit aby sme to zohladnovali. #93 
- [x] informacne emaily pre organizatorov. #99 
- [x] 1 den pred konanim udalosti odoslat email vsetkym registrovanym, "uz zajtra sa kona event!" #99 
- [x] subscribed checkbox pri registracii #98
- [x] suhlasim s podmienkami checkbox pri registracii #98
- [x] `default` template zdebugovat

Poziadavky z https://github.com/TIS2017/Nobelisti/blob/master/docs/katalog/katalog-poziadaviek.pdf
- [x] R-1-3-1 (na registracnej stranke ma byt info o mieste a case konania, jazyku v akom bude prednaska) --> toto sa da vyriesit cez jazykove subory
- [x] R-1-3-4 (notifikacny email po datume `notification threshold`)
- [x] R-1-3-5 (mazanie listka (soft delete) ak nebol do 24h potvrdeny)

Ked tieto veci budeme mat, mozme (pod mna) napisat Tomasovi, ze je to "done".

**Comment by Radcho** [comment]
- [ ] registration_open a daily_reminder test buttons (ak ma daily_reminder aj zmysel)
